spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          #将注册到nacos上的服务ID转小写
          lower-case-service-id: true
      routes:
         #oauth授权服务器zbf-auth-core
         - id: zbf-auth-core
           uri: lb://zbf-auth-core
           predicates:
           - Path=/auth/**
           filters:
             #表示去掉api前缀
             - StripPrefix=1
             - name: Hystrix
               args:
                    name: fallbackdd
                    fallbackUri: 'forward:/fallback'
         #资源服务器test-a-server2
         - id: zbf-user-server
           uri: lb://zbf-user-server
           predicates:
           - Path=/user/**
           filters:
             #表示去掉api前缀
             - StripPrefix=1
             - name: Hystrix
               args:
                    name: fallbackdd
                    fallbackUri: 'forward:/fallback'
hystrix.command.fallbackdd.execution.isolation.thread.timeoutInMilliseconds: 50000